'use strict';

export const REQUEST_CONCERTS = 'REQUEST_CONCERTS';
export const REQUEST_CONCERT = 'REQUEST_CONCERT';
export const RECEIVE_CONCERTS = 'RECEIVE_CONCERTS';
export const RECEIVE_CONCERT = 'RECEIVE_CONCERT';
export const SELECT_CONCERT = 'SELECT_CONCERT';

export const REQUEST_ARTISTS = 'REQUEST_ARTISTS';
export const REQUEST_ARTIST = 'REQUEST_ARTIST';
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST';
export const SELECT_ARTIST = 'SELECT_ARTIST'

export const REQUEST_REVIEWS = 'REQUEST_REVIEWS';
export const REQUEST_REVIEW = 'REQUEST_REVIEW';
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS';
export const RECEIVE_REVIEW = 'RECEIVE_REVIEW';
export const SELECT_REVIEW = 'SELECT_REVIEW';

export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SELECT_USER = 'SELECT_USER';

export const REQUEST_PHOTOS = 'REQUEST_PHOTOS';
export const REQUEST_PHOTO = 'REQUEST_PHOTO';
export const RECEIVE_PHOTOS = 'RECEIVE_PHOTOS';
export const RECEIVE_PHOTO = 'RECEIVE_PHOTO';
export const SELECT_PHOTO = 'SELECT_PHOTO';
